name: Build
on: workflow_dispatch

jobs:
  lk2nd:
    name: lk2nd
    uses: ./.github/workflows/lk2nd-matrix.yml
    with:
      project: lk2nd
      artifacts: |
        build-*/lk.bin
        build-*/lk2nd.img
        build-*/*
  lk1st:
    needs: lk2nd
    uses: ./.github/workflows/lk2nd-matrix.yml
    with:
      project: lk1st
      artifacts: |
        build-*/*.mbn
        build-*/lk.bin
        build-*/*
