name: Build
on: workflow_dispatch

jobs:
  # Build lk2nd-msm8916 separately first to avoid booting lots of runners
  # for obvious build errors that affect all platforms
  lk2nd-msm8996:
    name: lk2nd
    uses: ./.github/workflows/lk2nd.yml
    with:
      project: lk2nd
      platform: msm8996
      artifacts: |
        build-*/lk.bin
        build-*/lk2nd.img

  lk1st:
    needs: lk2nd-msm8996
    uses: ./.github/workflows/lk2nd.yml
    with:
      project: lk1st
      platform: msm8996
      artifacts: |
        build-*/*.mbn
        build-*/lk.bin

