name: Build stock matrix
on:
  workflow_call:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - msm8996
    uses: ./.github/workflows/stock.yml
    with:
      platform: ${{ matrix.platform }}
      options: ${{ matrix.options }}
