name: Build stock matrix
on:
  workflow_call:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - msm8996
        include:
          # No display support on msm8660/msm8960 (with mdp4)
          - platform: msm8660
            options: EMMC_BOOT=1 ENABLE_DISPLAY=0
          - platform: msm8960
            options: EMMC_BOOT=1 ENABLE_DISPLAY=0

    uses: ./.github/workflows/stock.yml
    with:
      platform: ${{ matrix.platform }}
      options: ${{ matrix.options }}
